runtime: nodejs16
service: nuxt-image
automatic_scaling:
  min_instances: 1

instance_class: F2

default_expiration: "365d"

inbound_services:
  - warmup

handlers:
  - url: /_nuxt
    static_dir: .output/public/_nuxt
    secure: always

  - url: /(.*\.(gif|png|jpg|ico))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico)$
    secure: always

  - url: /.*
    script: auto
    secure: always
